(() => {
  const labels=[['requests.read','مشاهدة الطلبات','View requests'],['requests.edit','تعديل الطلبات والصور','Edit requests & images'],['offers.read','مشاهدة العروض','View offers'],['offers.edit','تعديل العروض والصور','Edit offers & images'],['translate','الترجمة اليدوية','Manual translation'],['publish','الاعتماد والإرسال','Approve & publish'],['accounts.read','بيانات الحسابات والتواصل','Account contact details'],['accounts.manage','إدارة حسابات العملاء والموردين','Manage customer & supplier accounts'],['moderate','تعليق الطلبات','Suspend requests'],['trash','الحذف والاستعادة','Trash & restore'],['settings','النصوص والشعار','Text & logo'],['team','إدارة الفريق','Manage team']];
  function render(target){
    if(!M.can('team'))return;
    const E=W.escape,me=M.session(),admins=M.state().accounts.filter(a=>a.role==='admin');
    target.innerHTML='<div class="card-head"><h2>'+M.tr('فريق الإدارة','Admin team')+'</h2></div><div class="card-body"><p>'+M.tr('يجب أن يسجل المدير حسابًا ويؤكد بريده أولًا، ثم أضفه هنا.','The manager must register and verify their email first, then add them here.')+'</p><form id="teamForm"><input type="hidden" name="id"><label>'+M.tr('البريد الإلكتروني','Email')+'<input name="email" type="email" required></label><div class="permission-grid">'+labels.filter(([p])=>me.isOwner||me.permissions.includes(p)&&p!=='team').map(([p,ar,en])=>'<label class="check-row"><input type="checkbox" name="permission" value="'+p+'">'+M.tr(ar,en)+'</label>').join('')+'</div><p class="form-error"></p><button type="submit" class="btn btn-primary">'+M.tr('حفظ المدير وصلاحياته','Save manager & permissions')+'</button></form><div id="teamList">'+admins.map(a=>'<article class="invite-card"><h3>'+E(a.name||a.email)+'</h3><p>'+E(a.email||'')+'</p>'+W.badge(a.blockedAt?'blocked':'active')+(a.isOwner?'<p>'+M.tr('المدير الرئيسي — محمي','Owner — protected')+'</p>':a.id===me.id?'':'<button class="btn btn-outline" data-edit-admin="'+E(a.id)+'">'+M.tr('تعديل الصلاحيات','Edit permissions')+'</button> <button class="btn btn-outline" data-toggle-admin="'+E(a.id)+'">'+M.tr(a.blockedAt?'إلغاء الحظر':'حظر',a.blockedAt?'Unblock':'Block')+'</button>')+'</article>').join('')+'</div></div>';
    const form=target.querySelector('form');
    form.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await API.request('team',{id:form.elements.id.value||undefined,email:form.elements.email.value,permissions:[...form.querySelectorAll('[name="permission"]:checked')].map(x=>x.value),action:'save'});await API.refresh();render(target);}catch(err){form.querySelector('.form-error').textContent=err.message;}finally{button.disabled=false;}};
    target.querySelectorAll('[data-edit-admin]').forEach(b=>b.onclick=()=>{const a=admins.find(x=>x.id===b.dataset.editAdmin);form.elements.id.value=a.id;form.elements.email.value=a.email;form.querySelectorAll('[name="permission"]').forEach(c=>c.checked=a.permissions.includes(c.value));form.scrollIntoView({block:'center'});});
    target.querySelectorAll('[data-toggle-admin]').forEach(b=>b.onclick=async()=>{const a=admins.find(x=>x.id===b.dataset.toggleAdmin);if(!confirm(M.tr('تأكيد تغيير حالة المدير؟','Change this manager’s status?')))return;try{await API.request('team',{id:a.id,permissions:a.permissions,action:a.blockedAt?'unblock':'block'});await API.refresh();render(target);}catch(err){form.querySelector('.form-error').textContent=err.message;}});
  }
  window.Team={render};
})();
