import test from 'node:test';import assert from 'node:assert/strict';
import {defaultStore} from '../shared/storefront-model.mjs';
import {catalogConfig,catalogProducts,policyTemplates} from '../shared/catalog-controls.mjs';
import {normalizeStore} from '../backend/modules/studio.mjs';
import {upgradeStore} from '../backend/modules/storefront-upgrade.mjs';
import {renderStorefront,renderStoreRoute,renderStoreHeader,renderStoreFooter} from '../mobile-app/src/storefront.js';
const products=[{id:'1',status:'published',sku:'SKU-A',categoryId:'a',subcategoryId:'sub',country:'China',translation:{titleAr:'ألف',titleEn:'Alpha'},unitPrice:2,stock:0},{id:'2',status:'published',categoryId:'b',country:'China',translation:{titleAr:'باء',titleEn:'Beta'}},{id:'3',status:'pending',categoryId:'a'}];
function fixture(){const store=defaultStore();store.sections.unshift({id:'cats',type:'categories',visible:true,channel:'both',categoryIds:['b','a']});return {settings:{storefront:store,categories:[{id:'a',nameAr:'أ',nameEn:'A'},{id:'b',nameAr:'ب',nameEn:'B'},{id:'secret',nameAr:'مخفي',nameEn:'Secret',active:false}],subcategories:[{id:'sub',parentId:'a'}]},publicOffers:products};}
test('empty logo never renders a fallback; selected categories keep order and exclude hidden/unselected',()=>{const state=fixture();const html=renderStorefront(state,'web',{language:'en'});assert.doesNotMatch(html,/sf-brand-mark|>M<|data-store-category="secret"/);assert.ok(html.indexOf('data-store-category="b"')<html.indexOf('data-store-category="a"'));state.settings.storefront.sections[0].categoryIds=[];assert.doesNotMatch(renderStorefront(state,'web',{language:'en'}),/data-store-category=/);});
test('category pages contain only matching products, use common chrome, and reject hidden category',()=>{const state=fixture();const html=renderStoreRoute(state,{category:'a'},{language:'en'});assert.match(html,/data-store-product="1"/);assert.doesNotMatch(html,/data-store-product="2"|data-store-product="3"/);assert.ok(html.includes(renderStoreHeader(state,{language:'en'})));assert.ok(html.includes(renderStoreFooter(state,{language:'en'})));assert.doesNotMatch(renderStoreRoute(state,{category:'secret'},{language:'en'}),/data-store-product=/);});
test('catalog controls survive save/reload, search combines with all filters, and values are validated',()=>{const state=fixture(),s=state.settings.storefront.sections.find(s=>s.type==='catalog');s.catalog={showSearch:false,showAll:false,showCountries:false,showSort:false,showReset:false,categoryIds:['b','a'],subcategoryIds:['sub'],countryIds:['China'],pageSize:12};const saved=normalizeStore(state.settings.storefront);assert.equal(catalogConfig({storefront:saved}).showSearch,false);const html=renderStorefront({...state,settings:{...state.settings,storefront:saved}},'web',{language:'en'});assert.doesNotMatch(html,/type="search"|data-catalog-filter="country"|data-catalog-filter="sort"|data-catalog-reset|>All<\/option>/);assert.deepEqual(catalogProducts(products,{q:'sku-a',category:'a',subcategory:'sub',country:'China'}).map(p=>p.id),['1']);assert.equal(catalogProducts(products,{q:'sku-a',category:'b'}).length,0);assert.throws(()=>normalizeStore({...state.settings.storefront,sections:[{...s,catalog:{showSearch:'yes'}}]}));});
test('bilingual policies support ordering, hiding, deletion and safe rendering',()=>{const state=fixture();state.settings.storefront.pages=[{id:'p2',title:'ثاني',titleEn:'Second',content:'نص',contentEn:'<script>bad</script>',active:true,footer:true,policy:true},{id:'p1',title:'مخفي',titleEn:'Hidden',content:'سري',contentEn:'Hidden content',active:false,footer:true}];state.settings.storefront=normalizeStore(state.settings.storefront);const footer=renderStoreFooter(state,{language:'en'});assert.match(footer,/Second/);assert.doesNotMatch(footer,/Hidden/);assert.match(renderStoreRoute(state,{page:'p2'},{language:'en'}),/&lt;script&gt;/);assert.doesNotMatch(renderStoreRoute(state,{page:'p1'},{language:'en'}),/Hidden content/);state.settings.storefront.pages=[];assert.equal(upgradeStore(state.settings.storefront).pages.length,0);assert.ok(policyTemplates().every(p=>!p.active&&p.titleEn&&p.contentEn));});
