import test from 'node:test';import assert from 'node:assert/strict';
import {defaultStore} from '../shared/storefront-model.mjs';import {ensureThemePages,sectionsForPage,bannerHref} from '../shared/theme-pages.mjs';import {normalizeStore} from '../backend/modules/studio.mjs';import {catalogProducts} from '../shared/catalog-controls.mjs';import {renderStorefront,renderStoreRoute,renderStoreFooter} from '../mobile-app/src/storefront.js';
const fixture=()=>({settings:{storefront:ensureThemePages(defaultStore()),categories:[{id:'electronics',nameAr:'إلكترونيات',nameEn:'Electronics',active:true}],subcategories:[{id:'audio',parentId:'electronics',nameAr:'سماعات',nameEn:'Audio',active:true},{id:'cables',parentId:'electronics',nameAr:'كيابل',nameEn:'Cables',active:true},{id:'hidden',parentId:'electronics',active:false}],supplyCountries:[{id:'China',nameAr:'الصين',nameEn:'China'}]},publicOffers:[{id:'one',displayNo:123,sku:'TEST-1',status:'published',categoryId:'electronics',subcategoryId:'audio',country:'China',product:'Headphones',translation:{titleAr:'سماعة',titleEn:'Headphones',descriptionAr:'تفاصيل',descriptionEn:'Details'},unitPrice:10,moq:2,stock:100,leadTime:5,images:['/api/media/00000000-0000-4000-8000-000000000001','/api/media/00000000-0000-4000-8000-000000000002'],tiers:[{min:10,price:8}],keywords:['wireless']},{id:'two',status:'published',categoryId:'electronics',subcategoryId:'cables',product:'Cable',unitPrice:3},{id:'secret',status:'review',categoryId:'electronics'}]});
test('theme page upgrade is idempotent and page order/visibility survive normalization',()=>{const state=fixture(),s=state.settings.storefront;assert.deepEqual(ensureThemePages(s),s);const blocks=sectionsForPage(s,'product');assert.deepEqual(blocks.map(x=>x.type),['productCategories','breadcrumb','gallery','productInfo','productDetails','related','recommended']);blocks[0].visible=false;s.sections.splice(s.sections.indexOf(blocks[2]),1);s.sections.push(blocks[2]);const saved=normalizeStore(s);assert.equal(sectionsForPage(saved,'product').at(-1).type,'gallery');assert.equal(sectionsForPage(saved,'product')[0].visible,false);assert.equal(sectionsForPage(saved,'home').length,3);assert.equal(saved.sections.filter(s=>s.type==='header').length,1);assert.throws(()=>normalizeStore({...s,sections:[...s.sections,{...blocks[3],id:'duplicate'}]}));});
test('header search replaces filter box; searches combine product identity, category labels and keywords',()=>{const state=fixture(),html=renderStorefront(state,'web',{language:'en',route:{}});assert.match(html,/data-store-search/);assert.match(html,/name="q"[^>]*placeholder="Search"/);assert.doesNotMatch(html,/data-catalog-filter|sf-catalog-tools/);for(const q of ['TEST-1','123','wireless','Headphones','Audio'])assert.deepEqual(catalogProducts(state.publicOffers,{q},state.settings).map(x=>x.id),['one']);assert.equal(catalogProducts(state.publicOffers,{q:'Electronics'},state.settings).length,2);});
test('main and subcategory pages share sibling navigation with active subcategory and accurate products',()=>{const state=fixture();for(const language of ['ar','en']){const main=renderStoreRoute(state,{category:'electronics'},{language});assert.match(main,/category=audio/);assert.match(main,/category=cables/);assert.doesNotMatch(main,/category=hidden/);const sub=renderStoreRoute(state,{category:'audio'},{language});assert.match(sub,/data-store-category="audio" aria-current="page"/);assert.match(sub,/data-store-product="one"/);assert.doesNotMatch(sub,/data-store-product="two"|data-store-product="secret"/);}});
test('standalone product has gallery, purchase controls, details and siblings; unpublished products are unavailable',()=>{const state=fixture();for(const language of ['ar','en']){const html=renderStoreRoute(state,{product:'one'},{language});assert.match(html,/data-detail-product="one"/);assert.match(html,/data-gallery-index="1"/);assert.match(html,/data-product-purchase/);assert.match(html,/min="2"/);assert.match(html,/sf-detail-accordion/);assert.match(html,/category=audio/);assert.doesNotMatch(html,/role="dialog"/);assert.match(html,new RegExp('dir="'+(language==='ar'?'rtl':'ltr')+'"'));}assert.doesNotMatch(renderStoreRoute(state,{product:'secret'},{language:'en'}),/data-product-purchase/);});
test('banner destinations, optional CTA and footer group order persist without duplicate banner data',()=>{const state=fixture(),s=state.settings.storefront;s.banners=[{id:'b',title:'Offer',subtitle:'',image:'/api/media/00000000-0000-4000-8000-000000000001',active:true,channel:'both',targetType:'product',targetId:'one',showButton:false,button:'BUY'}];s.sections.push({id:'slider',type:'banners',page:'home',visible:true,channel:'both'});s.sections.find(x=>x.type==='footer').footerGroups=['shop','company'];const saved=normalizeStore(s);assert.equal(saved.banners.length,1);assert.equal(bannerHref(saved.banners[0]),'/?product=one');const html=renderStorefront({...state,settings:{...state.settings,storefront:saved}},'web',{language:'en',route:{}});assert.match(html,/sf-banner-slider/);assert.doesNotMatch(html,/>BUY</);const footer=renderStoreFooter({...state,settings:{...state.settings,storefront:saved}},{language:'en'});assert.ok(footer.indexOf('Explore the store')<footer.indexOf('MIG COMPANY'));});

test('page catalogs keep independent settings and channel visibility; footer titles and navigation visibility persist',()=>{
 const state=fixture(),store=state.settings.storefront;
 store.sections.find(s=>s.page==='search'&&s.type==='catalog').catalog={pageSize:12};
 store.sections.find(s=>s.type==='gallery').channel='app';
 const footer=store.sections.find(s=>s.type==='footer');footer.footerTitles={shop:'تسوق',shopEn:'Our products',policiesEn:'Legal'};
 store.links=[{id:'hidden-link',title:'مخفي',titleEn:'Hidden link',target:'products',active:false}];
 state.settings.storefront=normalizeStore(store);
 const html=renderStoreRoute(state,{page:'search',q:'Audio'},{language:'en'});assert.match(html,/data-catalog-section="search-catalog"/);
 assert.equal(state.settings.storefront.sections.find(s=>s.id==='search-catalog').catalog.pageSize,12);
 assert.doesNotMatch(renderStoreRoute(state,{product:'one'},{language:'en'}),/data-viewer-gallery/);
 assert.match(renderStorefront(state,'app',{route:{product:'one'},language:'en'}),/data-viewer-gallery/);
 assert.match(html,/Our products/);assert.doesNotMatch(html,/Hidden link/);
});
