const ADMIN_API='https://m-platform-tan.vercel.app';
const baseFetch=window.fetch.bind(window);
let accessToken='',refreshToken='',state=null,revision=0;
let requestTab='pending',offerTab='pending',searchText='',timer=null;
const mediaCache=new Map();
const lang=()=>document.documentElement.lang==='en'?'en':'ar';
const tr=(ar,en)=>lang()==='ar'?ar:en;
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const ref=x=>x?.displayNo||String(x?.id||'').slice(0,8)||'—';
const date=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat(lang()==='ar'?'ar':'en',{dateStyle:'medium'}).format(d);};
const me=()=>state?.user;
const isAdmin=()=>me()?.role==='admin';
const can=p=>!!(me()&&(me().isOwner||me().permissions?.includes(p)));
const account=id=>(state?.accounts||[]).find(a=>a.id===id);
const ownerOf=x=>account(x?.customerId||x?.supplierId);
const title=x=>{const t=x?.translation||{};return(lang()==='ar'?(t.titleAr||t.titleEn):(t.titleEn||t.titleAr))||x?.product||x?.title||`#${ref(x)}`;};
const desc=x=>{const t=x?.translation||{};return(lang()==='ar'?(t.descriptionAr||t.descriptionEn):(t.descriptionEn||t.descriptionAr))||x?.specs||x?.notes||'';};
const status=s=>({review:tr('قيد المراجعة','Under review'),sent:tr('تم الإرسال للموردين','Sent to suppliers'),completed:tr('مكتمل','Completed'),pending:tr('قيد المراجعة','Under review'),published:tr('منشور','Published'),coordinating:tr('قيد التنسيق','Coordinating'),accepted:tr('مقبول','Accepted'),cancelled:tr('ملغي','Cancelled')})[s]||s||'—';

async function capture(input,init,res){
  try{
    const url=typeof input==='string'?input:input?.url||'';
    const h=new Headers(init?.headers||{}),bearer=h.get('Authorization')?.match(/^Bearer\s+(.+)$/i)?.[1];if(bearer)accessToken=bearer;
    if(!res.ok)return;
    if(url.includes('/api/v1/auth/login')||url.includes('/api/v1/auth/refresh')){const d=await res.clone().json();accessToken=d.tokens?.accessToken||accessToken;refreshToken=d.tokens?.refreshToken||refreshToken;}
    if(url.includes('/api/v1/state')){const d=await res.clone().json();if(d?.user?.role==='admin'){state=d;revision++;schedule();}}
  }catch{}
}
window.fetch=async(input,init={})=>{const r=await baseFetch(input,init);await capture(input,init,r);return r;};
async function refresh(){if(!refreshToken)return false;const r=await baseFetch(ADMIN_API+'/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json','X-M-Client':'native'},body:JSON.stringify({refreshToken})});if(!r.ok)return false;const d=await r.json();accessToken=d.tokens?.accessToken||'';refreshToken=d.tokens?.refreshToken||refreshToken;return!!accessToken;}
async function api(path,{method='GET',body}={}){const h={'X-M-Client':'native'};if(body!==undefined)h['Content-Type']='application/json';if(accessToken)h.Authorization=`Bearer ${accessToken}`;let r=await baseFetch(ADMIN_API+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401&&await refresh()){h.Authorization=`Bearer ${accessToken}`;r=await baseFetch(ADMIN_API+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
async function reload(){const d=await api('/api/v1/state');if(d?.user?.role==='admin'){state=d;revision++;}return state;}
async function mutate(collection,item,patch,redactionConfirmed=false){await api('/api/v1/mutations',{method:'POST',body:{collection,id:item.id,version:Number(item.version||0),patch,redactionConfirmed}});await reload();}

function toast(msg){const e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2400);}
function activeView(){return document.querySelector('#bottomNav button.active')?.dataset.screen||'home';}
function rootKey(view){return [view,lang(),revision,searchText,requestTab,offerTab].join('|');}
function screen(){return document.getElementById('screen');}
function setRoot(view,html){const s=screen(),key=rootKey(view);if(!s)return;if(s.querySelector(`[data-admin-root="${view}"][data-admin-key="${CSS.escape(key)}"]`))return;s.innerHTML=`<div data-admin-root="${view}" data-admin-key="${esc(key)}">${html}</div>`;hydrate(s);}
function schedule(){clearTimeout(timer);timer=setTimeout(render,25);}
function badge(s){return`<span class="status-pill status-${esc(s||'')}">${esc(status(s))}</span>`;}
function page(title,sub=''){return`<div class="page-head admin-page-head"><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div></div>`;}
function empty(){return`<div class="empty-state"><span>◇</span><p>${esc(tr('لا توجد بيانات حاليًا.','No data available.'))}</p></div>`;}
function search(placeholder){return`<label class="admin-mobile-search"><span>⌕</span><input data-admin-search value="${esc(searchText)}" placeholder="${esc(placeholder)}"></label>`;}
function gallery(images=[],select=false){if(!images.length)return'';return`<div class="admin-image-grid">${images.map((src,i)=>`<label class="admin-image-tile"><input ${select?'':'disabled'} checked type="checkbox" data-admin-image-index="${i}"><span><img alt="" data-admin-media="${esc(src)}"></span>${select?`<small>${esc(tr('إبقاء الصورة','Keep image'))}</small>`:''}</label>`).join('')}</div>`;}
async function imageUrl(src){if(mediaCache.has(src))return mediaCache.get(src);const p=String(src).replace(/^\/api\/media\//,'/api/v1/media/'),h={'X-M-Client':'native'};if(accessToken)h.Authorization=`Bearer ${accessToken}`;const r=await baseFetch(ADMIN_API+p,{headers:h});if(!r.ok)return'';const u=URL.createObjectURL(await r.blob());mediaCache.set(src,u);return u;}
async function hydrate(root=document){for(const img of root.querySelectorAll('img[data-admin-media]:not([data-loaded])')){img.dataset.loaded='1';try{const u=await imageUrl(img.dataset.adminMedia);if(u)img.src=u;}catch{}}}
function row(x,kind){const o=ownerOf(x),linked=kind==='quote'?(state?.requests||[]).find(r=>r.id===x.requestId):null;return`<article class="list-card admin-record-card" data-admin-open="${kind}" data-admin-id="${esc(x.id)}"><div class="list-card-main"><div class="list-card-title"><small>#${esc(ref(x))}</small><h3>${esc(title(x))}</h3></div>${badge(x.status)}</div>${desc(x)?`<p>${esc(desc(x))}</p>`:''}<div class="admin-record-meta">${o?`<span>${esc(o.company||o.name||tr('صاحب المحتوى','Owner'))}</span>`:''}${linked?`<span>#${esc(ref(linked))}</span>`:''}<span>${esc(date(x.createdAt))}</span></div>${gallery(x.images||[])}</article>`;}
function matches(x,kind=''){if(!searchText.trim())return true;const q=searchText.trim().toLowerCase(),o=ownerOf(x),linked=kind==='quote'?(state?.requests||[]).find(r=>r.id===x.requestId):null,client=linked?account(linked.customerId):null;return[ref(x),x.name,x.company,x.email,x.phone,x.product,x.specs,x.notes,x.country,o?.name,o?.company,linked?.displayNo,client?.name,client?.company].filter(Boolean).join(' ').toLowerCase().includes(q);}

function home(){const req=state?.requests||[],qs=state?.quotes||[],po=state?.publicOffers||[],ints=state?.interests||[],acc=state?.accounts||[],pr=req.filter(x=>!x.deletedAt&&!x.suspendedAt&&x.status==='review'),offers=[...qs.map(x=>({...x,__kind:'quote'})),...po.map(x=>({...x,__kind:'public'}))].filter(x=>!x.deletedAt&&x.status==='pending'),priority=[...pr.slice(0,3).map(x=>row(x,'request')),...offers.slice(0,3).map(x=>row(x,x.__kind))].join('');setRoot('home',page(tr('لوحة الإدارة','Admin dashboard'),tr('اعتماد الطلبات والعروض ومتابعة المنصة من الجوال.','Approve requests and offers and monitor the platform from mobile.'))+`<div class="stats-grid admin-stats"><button class="stat-card" data-admin-go="requests"><strong>${pr.length}</strong><span>${esc(tr('طلبات بانتظار الاعتماد','Requests pending approval'))}</span></button><button class="stat-card" data-admin-go="offers"><strong>${offers.length}</strong><span>${esc(tr('عروض بانتظار الاعتماد','Offers pending approval'))}</span></button><button class="stat-card" data-admin-go="offers" data-admin-tab-target="interests"><strong>${ints.length}</strong><span>${esc(tr('طلبات الاهتمام','Interest requests'))}</span></button><button class="stat-card" data-admin-go="account"><strong>${acc.filter(a=>['client','supplier'].includes(a.role)&&!a.deletedAt).length}</strong><span>${esc(tr('العملاء والموردون','Customers & suppliers'))}</span></button></div><section class="section-block"><div class="section-title"><h2>${esc(tr('الأولوية الآن','Priority now'))}</h2></div><div class="list-stack">${priority||empty()}</div></section>`);}
function requests(){let rows=(state?.requests||[]).filter(x=>!x.deletedAt&&!x.suspendedAt&&matches(x,'request'));rows.sort((a,b)=>(a.status==='review'?0:1)-(b.status==='review'?0:1)||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));if(requestTab==='pending')rows=rows.filter(x=>x.status==='review');setRoot('requests',page(tr('الطلبات','Requests'),tr('راجع الطلب وحدد الموردين ثم اعتمده مباشرة.','Review the request, assign suppliers, then approve it directly.'))+search(tr('ابحث برقم الطلب أو اسم العميل','Search request number or customer'))+`<div class="segmented admin-segmented"><button class="${requestTab==='pending'?'active':''}" data-admin-request-tab="pending">${esc(tr('بانتظار الاعتماد','Pending'))}</button><button class="${requestTab==='all'?'active':''}" data-admin-request-tab="all">${esc(tr('جميع الطلبات','All requests'))}</button></div><div class="list-stack">${rows.map(x=>row(x,'request')).join('')||empty()}</div>`);}
function offers(){const qs=(state?.quotes||[]).filter(x=>!x.deletedAt).map(x=>({...x,__kind:'quote'})),po=(state?.publicOffers||[]).filter(x=>!x.deletedAt).map(x=>({...x,__kind:'public'})),ints=state?.interests||[];let content='';if(offerTab==='interests'){const rows=ints.filter(x=>matches(x,'interest'));content=rows.map(i=>{const o=(state?.publicOffers||[]).find(x=>x.id===i.offerId),c=account(i.customerId);return`<article class="list-card admin-interest-card"><div class="list-card-main"><div class="list-card-title"><small>#${esc(ref(o))}</small><h3>${esc(o?title(o):tr('طلب اهتمام','Interest request'))}</h3></div>${badge(i.status||'pending')}</div><div class="admin-record-meta">${c?`<span>${esc(c.company||c.name||'')}</span>`:''}<span>${esc(date(i.createdAt))}</span></div>${can('publish')?`<label class="admin-status-select"><span>${esc(tr('الحالة','Status'))}</span><select data-admin-interest-status="${esc(i.id)}">${['pending','coordinating','accepted','completed','cancelled'].map(v=>`<option value="${v}" ${(i.status||'pending')===v?'selected':''}>${esc(status(v))}</option>`).join('')}</select></label>`:''}</article>`;}).join('')||empty();}else{let rows=[...qs,...po].filter(x=>matches(x,x.__kind));rows.sort((a,b)=>(a.status==='pending'?0:1)-(b.status==='pending'?0:1)||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));if(offerTab==='pending')rows=rows.filter(x=>x.status==='pending');content=rows.map(x=>row(x,x.__kind)).join('')||empty();}setRoot('offers',page(tr('العروض','Offers'),tr('مراجعة عروض الموردين والعروض العامة وإدارة طلبات الاهتمام.','Review supplier quotes, public offers, and interest requests.'))+search(tr('ابحث برقم العرض أو اسم المورد','Search offer number or supplier'))+`<div class="segmented admin-segmented admin-segmented-3"><button class="${offerTab==='pending'?'active':''}" data-admin-offer-tab="pending">${esc(tr('بانتظار الاعتماد','Pending'))}</button><button class="${offerTab==='all'?'active':''}" data-admin-offer-tab="all">${esc(tr('كل العروض','All offers'))}</button><button class="${offerTab==='interests'?'active':''}" data-admin-offer-tab="interests">${esc(tr('الاهتمام','Interest'))}</button></div><div class="list-stack">${content}</div>`);}
function accounts(){const u=me(),rows=(state?.accounts||[]).filter(a=>['client','supplier'].includes(a.role)&&!a.deletedAt&&matches(a,'account'));setRoot('account',page(tr('الإدارة والحسابات','Admin & accounts'),tr('بيانات حسابك ودليل العملاء والموردين.','Your profile and customer/supplier directory.'))+`<section class="profile-card admin-profile"><div class="avatar">${esc((u?.name||u?.email||'M').charAt(0).toUpperCase())}</div><h2>${esc(u?.name||tr('الإدارة','Admin'))}</h2><p>${esc(tr('حساب إدارة','Admin account'))}</p><button class="danger-btn" data-action="logout">${esc(tr('تسجيل الخروج','Sign out'))}</button></section><section class="section-block admin-directory"><div class="section-title"><h2>${esc(tr('العملاء والموردون','Customers & suppliers'))}</h2></div>${search(tr('ابحث بالاسم أو الشركة','Search name or company'))}<div class="list-stack">${rows.slice(0,100).map(a=>`<button class="admin-account-row" data-admin-account="${esc(a.id)}"><div><strong>${esc(a.company||a.name||'#'+String(a.id).slice(0,8))}</strong><small>${esc(a.role==='client'?tr('عميل','Customer'):tr('مورد','Supplier'))}</small></div><span>›</span></button>`).join('')||empty()}</div></section>`);}
function render(){if(!isAdmin()||document.getElementById('appView')?.classList.contains('hidden'))return;const v=activeView();if(v==='notifications')return;if(v==='home')home();else if(v==='requests')requests();else if(v==='offers')offers();else if(v==='account')accounts();}

function modal(titleText,kicker,html){const m=document.getElementById('modal');if(!m)return;document.getElementById('modalTitle').textContent=titleText;document.getElementById('modalKicker').textContent=kicker||'';document.getElementById('modalBody').innerHTML=html;m.classList.remove('hidden');hydrate(document.getElementById('modalBody'));}
function closeModal(){document.getElementById('modal')?.classList.add('hidden');}
function ownerBox(x){const o=ownerOf(x);if(!o)return'';return`<section class="admin-owner-box"><strong>${esc(tr('صاحب المحتوى','Content owner'))}</strong><p>${esc(o.company||o.name||'#'+String(o.id).slice(0,8))}</p>${can('accounts.read')?`<small>${esc(o.name||'')} ${o.phone?`· ${esc(o.phone)}`:''} ${o.email?`· ${esc(o.email)}`:''} ${o.country?`· ${esc(o.country)}`:''}</small>`:''}</section>`;}
function translations(x,editable){const t=x.translation||{},d=editable?'':'disabled';return`<div class="form-stack admin-translation"><label><span>${esc(tr('العنوان بالعربية','Arabic title'))}</span><input ${d} data-admin-tr="titleAr" value="${esc(t.titleAr||'')}"></label><label><span>${esc(tr('العنوان بالإنجليزية','English title'))}</span><input ${d} data-admin-tr="titleEn" value="${esc(t.titleEn||'')}"></label><label><span>${esc(tr('الوصف بالعربية','Arabic description'))}</span><textarea ${d} data-admin-tr="descriptionAr">${esc(t.descriptionAr||'')}</textarea></label><label><span>${esc(tr('الوصف بالإنجليزية','English description'))}</span><textarea ${d} data-admin-tr="descriptionEn">${esc(t.descriptionEn||'')}</textarea></label></div>`;}
function supplierPicker(x){const s=(state?.accounts||[]).filter(a=>a.role==='supplier'&&!a.deletedAt&&!a.blockedAt);return`<section class="admin-supplier-picker"><h3>${esc(tr('الموردون المدعوون','Invited suppliers'))}</h3><div class="admin-check-list">${s.map(a=>`<label><input type="checkbox" data-admin-supplier value="${esc(a.id)}" ${(x.supplierIds||[]).includes(a.id)?'checked':''}><span>${esc(a.company||a.name||'#'+String(a.id).slice(0,8))}</span></label>`).join('')}</div></section>`;}
function openRecord(kind,id){const arr=kind==='request'?state?.requests:kind==='quote'?state?.quotes:state?.publicOffers,x=(arr||[]).find(v=>v.id===id);if(!x)return;const pending=kind==='request'?x.status==='review':x.status==='pending',editPerm=kind==='request'?'requests.edit':'offers.edit',editImages=pending&&can(editPerm),editTr=pending&&can('translate'),approve=pending&&can('publish'),linked=kind==='quote'?(state?.requests||[]).find(r=>r.id===x.requestId):null;let html=ownerBox(x)+`<section class="admin-source-box"><h3>${esc(tr('المحتوى الأصلي','Original content'))}</h3><strong>${esc(x.product||linked?.product||title(x))}</strong><p>${esc(x.specs||x.notes||'—')}</p>${kind==='request'?`<div class="facts"><span>${esc(tr('الكمية','Quantity'))}: ${esc(x.quantity||'—')}</span><span>${esc(tr('الدولة','Country'))}: ${esc(x.country||'—')}</span><span>${esc(tr('تاريخ الاحتياج','Needed date'))}: ${esc(x.neededDate||'—')}</span></div>`:''}${linked?`<div class="facts"><span>${esc(tr('الطلب المرتبط','Linked request'))}: #${esc(ref(linked))}</span></div>`:''}</section><section><h3>${esc(tr('الصور','Images'))}</h3>${gallery(x.images||[],editImages)||`<p class="muted">${esc(tr('لا توجد صور.','No images.'))}</p>`}</section><section><h3>${esc(tr('الترجمة','Translation'))}</h3>${translations(x,editTr)}</section>`;if(kind==='request'&&pending&&can('publish'))html+=supplierPicker(x);if(pending){html+=`<section class="admin-redaction"><h3>${esc(tr('فحص الخصوصية','Privacy check'))}</h3><label><input type="checkbox" data-admin-redact="identity"><span>${esc(tr('تمت مراجعة الصور والنصوص وإزالة الهوية.','Images and text were checked and identity removed.'))}</span></label><label><input type="checkbox" data-admin-redact="contact"><span>${esc(tr('تمت إزالة بيانات التواصل المباشر.','Direct contact details were removed.'))}</span></label></section><div class="admin-review-actions">${editTr?`<button class="secondary-btn" data-admin-save-review data-kind="${kind}" data-id="${esc(x.id)}">${esc(tr('حفظ دون نشر','Save without publishing'))}</button>`:''}${approve?`<button class="primary-btn" data-admin-approve data-kind="${kind}" data-id="${esc(x.id)}">${esc(tr('اعتماد ونشر','Approve & publish'))}</button>`:''}</div>`;}else if(kind==='request'&&x.status==='sent'&&can('publish'))html+=`<div class="admin-review-actions"><button class="secondary-btn" data-admin-reopen-request data-id="${esc(x.id)}">${esc(tr('إعادة للمراجعة','Return to review'))}</button><button class="primary-btn" data-admin-complete-request data-id="${esc(x.id)}">${esc(tr('تحديد كمكتمل','Mark completed'))}</button></div>`;modal(`#${ref(x)} — ${title(x)}`,status(x.status),html);}
function openAccount(id){const a=account(id);if(!a)return;const req=(state?.requests||[]).filter(r=>r.customerId===id),qs=(state?.quotes||[]).filter(q=>q.supplierId===id),po=(state?.publicOffers||[]).filter(o=>o.supplierId===id);modal(a.company||a.name||'#'+String(a.id).slice(0,8),a.role==='client'?tr('عميل','Customer'):tr('مورد','Supplier'),`<dl class="admin-account-details"><div><dt>${esc(tr('الاسم','Name'))}</dt><dd>${esc(a.name||'—')}</dd></div><div><dt>${esc(tr('الشركة','Company'))}</dt><dd>${esc(a.company||'—')}</dd></div><div><dt>${esc(tr('رقم التواصل','Phone'))}</dt><dd>${esc(a.phone||'—')}</dd></div><div><dt>${esc(tr('البريد','Email'))}</dt><dd>${esc(a.email||'—')}</dd></div><div><dt>${esc(tr('الدولة','Country'))}</dt><dd>${esc(a.country||'—')}</dd></div></dl><h3>${esc(tr('السجل','History'))}</h3><div class="facts"><span>${esc(tr('الطلبات','Requests'))}: ${req.length}</span><span>${esc(tr('العروض','Offers'))}: ${qs.length+po.length}</span></div>`);}
function readForm(x){const translation={};document.querySelectorAll('[data-admin-tr]').forEach(e=>translation[e.dataset.adminTr]=e.value.trim());const images=[];(x.images||[]).forEach((src,i)=>{const b=document.querySelector(`[data-admin-image-index="${i}"]`);if(!b||b.checked)images.push(src);});return{translation,images,suppliers:[...document.querySelectorAll('[data-admin-supplier]:checked')].map(e=>e.value),identity:document.querySelector('[data-admin-redact="identity"]')?.checked,contact:document.querySelector('[data-admin-redact="contact"]')?.checked};}
async function approve(kind,id){const arr=kind==='request'?state.requests:kind==='quote'?state.quotes:state.publicOffers,x=arr.find(v=>v.id===id);if(!x)return;const f=readForm(x);if(Object.values(f.translation).some(v=>!v)){toast(tr('أكمل العنوان والوصف بالعربية والإنجليزية.','Complete Arabic and English title and description.'));return;}if(!f.identity||!f.contact){toast(tr('أكمل فحص إزالة الهوية وبيانات التواصل.','Complete both privacy checks.'));return;}if(kind==='request'&&!f.suppliers.length){toast(tr('اختر موردًا واحدًا على الأقل.','Select at least one supplier.'));return;}const patch={translation:f.translation,reviewedAt:new Date().toISOString(),status:kind==='request'?'sent':'published'},editPerm=kind==='request'?'requests.edit':'offers.edit';if(can(editPerm))patch.images=f.images;if(kind==='request')patch.supplierIds=f.suppliers;try{await mutate(kind==='request'?'requests':kind==='quote'?'quotes':'publicOffers',x,patch,true);closeModal();schedule();toast(tr('تم الاعتماد بنجاح.','Approved successfully.'));}catch(e){toast(e.message);}}
async function saveReview(kind,id){const arr=kind==='request'?state.requests:kind==='quote'?state.quotes:state.publicOffers,x=arr.find(v=>v.id===id);if(!x)return;const f=readForm(x);if(Object.values(f.translation).some(v=>!v)){toast(tr('أكمل الترجمة أولًا.','Complete the translation first.'));return;}const patch={translation:f.translation,reviewedAt:new Date().toISOString()},editPerm=kind==='request'?'requests.edit':'offers.edit';if(can(editPerm))patch.images=f.images;try{await mutate(kind==='request'?'requests':kind==='quote'?'quotes':'publicOffers',x,patch);closeModal();schedule();toast(tr('تم حفظ المراجعة.','Review saved.'));}catch(e){toast(e.message);}}
async function requestStatus(id,s){const x=(state?.requests||[]).find(v=>v.id===id);if(!x)return;try{await mutate('requests',x,{status:s});closeModal();schedule();toast(tr('تم تحديث الحالة.','Status updated.'));}catch(e){toast(e.message);}}
async function interestStatus(id,s){const x=(state?.interests||[]).find(v=>v.id===id);if(!x)return;try{await mutate('interests',x,{status:s});schedule();toast(tr('تم تحديث الحالة.','Status updated.'));}catch(e){toast(e.message);}}
function go(view,tab){if(view==='offers'&&tab)offerTab=tab;document.querySelector(`#bottomNav button[data-screen="${view}"]`)?.click();setTimeout(schedule,30);}

document.addEventListener('click',e=>{if(e.target.closest('#appLangBtn')||e.target.closest('#bottomNav button[data-screen]'))setTimeout(schedule,30);const g=e.target.closest('[data-admin-go]');if(g){go(g.dataset.adminGo,g.dataset.adminTabTarget);return;}const rt=e.target.closest('[data-admin-request-tab]');if(rt){requestTab=rt.dataset.adminRequestTab;schedule();return;}const ot=e.target.closest('[data-admin-offer-tab]');if(ot){offerTab=ot.dataset.adminOfferTab;schedule();return;}const o=e.target.closest('[data-admin-open]');if(o){openRecord(o.dataset.adminOpen,o.dataset.adminId);return;}const a=e.target.closest('[data-admin-account]');if(a){openAccount(a.dataset.adminAccount);return;}const ap=e.target.closest('[data-admin-approve]');if(ap){approve(ap.dataset.kind,ap.dataset.id);return;}const sv=e.target.closest('[data-admin-save-review]');if(sv){saveReview(sv.dataset.kind,sv.dataset.id);return;}const rr=e.target.closest('[data-admin-reopen-request]');if(rr){requestStatus(rr.dataset.id,'review');return;}const cr=e.target.closest('[data-admin-complete-request]');if(cr){requestStatus(cr.dataset.id,'completed');return;}});
document.addEventListener('input',e=>{if(e.target.matches('[data-admin-search]')){searchText=e.target.value;schedule();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-admin-interest-status]'))interestStatus(e.target.dataset.adminInterestStatus,e.target.value);});
window.addEventListener('DOMContentLoaded',()=>{const obs=new MutationObserver(schedule),app=document.getElementById('app');if(app)obs.observe(app,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});obs.observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir']});});