import './storefront.css';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=p=>p.translation?.[document.documentElement.lang==='en'?'titleEn':'titleAr']||p.translation?.titleAr||'';
const media=src=>/^\/api\/media\/[a-f0-9-]{36}$/.test(src||'')?src:'';
export const stageNames=['التحقق من توفر البضاعة','بانتظار الدفع','قيد التجهيز','جاهز للفحص والشحن','تم الشحن','في الطريق','التخليص الجمركي','قيد التوصيل','تم التسليم'];
const stageEnglish=['Checking availability','Awaiting payment','Preparing','Ready for inspection and shipping','Shipped','In transit','Customs clearance','Out for delivery','Delivered'];
export const stageLabel=i=>(document.documentElement.lang==='en'?stageEnglish:stageNames)[i]||'';
export function tierPrice(p,q){let price=Number(p.unitPrice);for(const t of p.tiers||[])if(q>=t.min)price=Number(t.price);return price;}
export function productExtras(p){return `<section class="product-extra">${[['',p.shortDescription],['المواصفات / Specifications',p.technicalSpecs],['الخيارات / Options',p.options],['ملاحظات / Notes',p.productNotes]].filter(([,v])=>v).map(([label,v])=>`${label?`<h3>${label}</h3>`:''}<p>${esc(v)}</p>`).join('')}${p.tiers?.length?`<h3>أسعار الجملة / Wholesale prices</h3><ul>${p.tiers.map(t=>`<li>${t.min}+ : ${t.price} ${esc(p.currency)}</li>`).join('')}</ul>`:''}</section>`;}
export function orderTimeline(o){return `<section class="flow-timeline">${o.cancelledAt?`<p>ملغى / Cancelled: ${esc(o.cancellationReason)}</p>`:''}<ol>${stageNames.map((n,i)=>{const event=(o.orderHistory||[]).find(h=>h.stage===i&&!h.cancelled);return `<li class="${i<o.orderStage?'done':i===o.orderStage?'current':''}" ${i===o.orderStage?'aria-current="step"':''}><strong>${esc(stageLabel(i))}</strong><small>${event?esc(new Date(event.at).toLocaleString()):'—'}</small></li>`}).join('')}</ol><p>${esc(o.carrier||'')} ${esc(o.trackingNumber||'')}</p><p>${esc(o.delivery?.country||'')} · ${esc(o.delivery?.address||'')}</p></section>`;}
export function renderStorefront(state,channel='web'){
  const config=state?.settings?.storefront;if(!config)return '';
  const t=config.theme||{},offers=(state.publicOffers||[]).filter(p=>p.status==='published'&&!p.deletedAt),color=/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#294c7a';
  const img=src=>media(src)?`<img src="${esc(src)}" data-media="${esc(src)}" alt="" loading="lazy">`:'';
  const today=new Date().toISOString().slice(0,10);
  return `<section class="published-storefront" style="--store-accent:${color};--store-radius:${[0,8,16,24].includes(t.round)?t.round:8}px"><div class="sf-announcement">${esc(t.announcement)}</div><header>${img(t.logo)}<div><h2>${esc(t.name)}</h2><p>${esc(t.tagline)}</p></div></header><nav>${(config.links||[]).map(l=>`<button type="button" data-store-page="${esc(l.target)}">${esc(l.title)}</button>`).join('')}</nav>${(config.sections||[]).filter(s=>s.visible&&(s.channel==='both'||s.channel===channel)).map(s=>{
    if(s.type==='hero')return `<section class="sf-hero">${img(s.image)}<div><h2>${esc(s.title)}</h2><p>${esc(s.subtitle)}</p><button type="button" data-store-page="products">${esc(s.button||'المنتجات')}</button></div></section>`;
    if(s.type==='text')return `<section><h3>${esc(s.title)}</h3><p>${esc(s.subtitle)}</p></section>`;
    if(s.type==='categories')return `<section><h3>${esc(s.title)}</h3><div class="sf-pills">${(state.settings.categories||[]).filter(c=>c.active!==false).map(c=>`<button type="button" data-store-category="${esc(c.id)}">${esc(document.documentElement.lang==='en'?c.nameEn:c.nameAr)}</button>`).join('')}</div></section>`;
    if(s.type==='banners')return `<section><h3>${esc(s.title)}</h3>${(config.banners||[]).filter(b=>b.active&&(b.channel==='both'||b.channel===channel)&&(!b.start||b.start<=today)&&(!b.end||b.end>=today)).map(b=>`<article class="sf-banner">${img(b.image)}<h3>${esc(b.title)}</h3><p>${esc(b.subtitle)}</p></article>`).join('')}</section>`;
    if(s.type==='products'){const group=(config.collections||[]).find(c=>c.id===s.collectionId);const rows=s.collectionId?(group?.active?group.productIds.map(id=>offers.find(p=>p.id===id)).filter(Boolean):[]):offers;return `<section><h3>${esc(s.title)}</h3><div class="sf-products">${rows.slice(0,s.limit||6).map(p=>`<button type="button" data-store-product="${esc(p.id)}">${img(p.images?.[0])}<strong>${esc(title(p))}</strong><span>${esc(p.unitPrice)} ${esc(p.currency)}</span><small>MOQ ${esc(p.moq)}</small></button>`).join('')}</div></section>`;}return '';
  }).join('')}</section>`;
}
export function bindStorefront(host,state,{product,page,category,catalog}){if(!host)return;host.onclick=e=>{const p=e.target.closest('[data-store-product]'),l=e.target.closest('[data-store-page]'),c=e.target.closest('[data-store-category]');if(p)product(p.dataset.storeProduct);if(c){category(c.dataset.storeCategory);catalog();}if(l){if(['home','products'].includes(l.dataset.storePage))catalog();else{const content=(state.settings.storefront.pages||[]).find(x=>x.id===l.dataset.storePage&&x.active);if(content)page(content.title,`<p class="long-copy">${esc(content.content)}</p>`);}}};}
