import {SECTION_DEFAULTS,normalizeSectionLayout,sectionDefaults} from '../../shared/section-layout.mjs';
export {SECTION_DEFAULTS,sectionDefaults};
import {homeConfig,defaultStore,selectSectionProducts,STORE_OPTIONS,safeStoreLink} from '../../shared/storefront-model.mjs';
export {homeConfig,defaultStore,STORE_OPTIONS};
export {selectSectionProducts};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=(p,lang=document.documentElement.lang)=>p.translation?.[lang==='en'?'titleEn':'titleAr']||p.translation?.titleAr||p.product||'';
const media=src=>/^\/api\/media\/[a-f0-9-]{36}$/.test(src||'')?src:'';
export const stageNames=['التحقق من توفر البضاعة','بانتظار الدفع','قيد التجهيز','جاهز للفحص والشحن','تم الشحن','في الطريق','التخليص الجمركي','قيد التوصيل','تم التسليم'];
const stageEnglish=['Checking availability','Awaiting payment','Preparing','Ready for inspection and shipping','Shipped','In transit','Customs clearance','Out for delivery','Delivered'];
export const stageLabel=i=>(document.documentElement.lang==='en'?stageEnglish:stageNames)[i]||'';
export function tierPrice(p,q){let price=Number(p.unitPrice);for(const t of p.tiers||[])if(q>=t.min)price=Number(t.price);return price;}
export function productExtras(p,h={showPrices:true}){return `<section class="product-extra">${[['',p.shortDescription],['المواصفات / Specifications',p.technicalSpecs],['الخيارات / Options',p.options],['ملاحظات / Notes',p.productNotes]].filter(([,v])=>v).map(([label,v])=>`${label?`<h3>${label}</h3>`:''}<p>${esc(v)}</p>`).join('')}${h.showPrices&&p.tiers?.length?`<h3>أسعار الجملة / Wholesale prices</h3><ul>${p.tiers.map(t=>`<li>${t.min}+ : ${t.price} ${esc(p.currency)}</li>`).join('')}</ul>`:''}</section>`;}
export function orderTimeline(o){return `<section class="flow-timeline">${o.cancelledAt?`<p>ملغى / Cancelled: ${esc(o.cancellationReason)}</p>`:''}<ol>${stageNames.map((n,i)=>{const event=(o.orderHistory||[]).find(h=>h.stage===i&&!h.cancelled);return `<li class="${i<o.orderStage?'done':i===o.orderStage?'current':''}" ${i===o.orderStage?'aria-current="step"':''}><strong>${esc(stageLabel(i))}</strong><small>${event?esc(new Date(event.at).toLocaleString()):'—'}</small></li>`}).join('')}</ol><p>${esc(o.carrier||'')} ${esc(o.trackingNumber||'')}</p><p>${esc(o.delivery?.country||'')} · ${esc(o.delivery?.address||'')}</p></section>`;}
const symbol=n=>({cart:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 3h2l3 12h10l3-9H6M9 21h.01M18 21h.01"/></svg>',arrow:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M19 12H5m6-6-6 6 6 6"/></svg>',box:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><path d="m3 7 9-5 9 5-9 5-9-5v10l9 5 9-5V7M12 12v10M7 4l10 6"/></svg>'}[n]);
export function storeProductCard(p,h,money,lang=document.documentElement.lang){const src=media(p.images?.[0]);return `<article class="sf-product"><button type="button" data-store-product="${esc(p.id)}" class="sf-product-visual" aria-label="${esc(title(p,lang))}">${h.showProductImage===false?'':src?`<img src="${esc(src)}" data-media="${esc(src)}" alt="${esc(title(p,lang))}" loading="lazy">`:`<span class="sf-placeholder">${symbol('box')}</span>`}<span class="sf-origin">${esc(p.country||'M Platform')}</span></button><div class="sf-product-copy"><button type="button" data-store-product="${esc(p.id)}" class="sf-product-name">${esc(title(p,lang))}</button><div class="sf-product-meta"><span>MOQ ${esc(p.moq||1)}</span>${h.showStock&&p.stock!==''&&p.stock!=null?`<span>${esc(lang==='en'?'Stock':'المخزون')}: ${esc(p.stock)}</span>`:''}</div><div class="sf-product-bottom">${h.showPrices?`<div class="sf-price"><strong>${money?money(p.unitPrice,p.currency):esc(new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(Number(p.unitPrice)||0))}</strong><small>${money?'':esc(p.currency||'')}</small></div>`:''}${h.showCart?`<button type="button" class="sf-add" data-store-add="${esc(p.id)}" aria-label="${esc(lang==='en'?'Add '+title(p,lang)+' to cart':'إضافة '+title(p,lang)+' إلى السلة')}">${symbol('cart')}<span>${lang==='en'?'Add to cart':'أضف للسلة'}</span></button>`:''}</div></div></article>`;}
export function renderStorefront(state,channel='web',options={}){
 const config=state?.settings?.storefront||defaultStore(),h=homeConfig(state?.settings),t=config.theme||{},lang=options.language||document.documentElement.lang,en=lang==='en';
 const localized=(o,k)=>o[k+(en?'En':'')]||o[k]||'',img=(src,cls='')=>media(src)?`<img class="${cls}" src="${esc(src)}" data-media="${esc(src)}" alt="" loading="lazy">`:'';
 const color=/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#193d43',name=t.name||'M Platform';
 const button=s=>!s.showButton||!localized(s,'button')?'':s.buttonTarget==='link'?(s.href&&safeStoreLink(s.href)?`<a class="sf-primary" href="${esc(s.href)}">${esc(localized(s,'button'))}</a>`:''):`<button class="sf-primary" type="button" ${s.buttonTarget==='products'?`data-store-browse="${esc(s.id)}"`:`data-store-action="${esc(s.buttonTarget)}"`}>${esc(localized(s,'button'))}${symbol('arrow')}</button>`;
 const allButton=`<button type="button" class="sf-all-products" data-store-browse="all">${en?'View all products':'عرض جميع المنتجات'}</button>`;
 const hit=s=>!s.clickable?'':s.buttonTarget==='link'?(s.href&&safeStoreLink(s.href)?`<a class="sf-banner-hit" href="${esc(s.href)}" aria-label="${esc(localized(s,'title')||localized(s,'button')||(en?'Open banner':'فتح البنر'))}"></a>`:''):`<button type="button" class="sf-banner-hit" ${s.buttonTarget==='products'?`data-store-browse="${esc(s.id)}"`:`data-store-action="${esc(s.buttonTarget)}"`} aria-label="${esc(localized(s,'title')||localized(s,'button')||(en?'Open banner':'فتح البنر'))}"></button>`;
 const header=options.client?'':`<header class="sf-header"><a href="#" data-store-action="home" class="sf-brand">${img(t.logo)||'<span class="sf-brand-mark">M</span>'}<span>${esc(name)}<small>${esc(localized(t,'tagline'))}</small></span></a><div class="sf-header-actions">${h.showCart?`<button type="button" class="sf-cart-button" aria-label="${en?'Cart':'السلة'}" data-store-action="cart">${symbol('cart')}<span>${en?'Cart':'السلة'}</span><b data-store-cart-count>${Number(options.cartCount)||0}</b></button>`:''}${h.showLogin?`<button type="button" data-store-action="login">${en?'Sign in':'تسجيل الدخول'}</button>`:''}<button type="button" data-store-action="language">${en?'العربية':'EN'}</button></div></header>`;
 const today=new Date().toISOString().slice(0,10);
 const blocks=(config.sections||[]).filter(s=>s.visible&&(s.channel==='both'||s.channel===channel)).map((raw,index)=>{
  const s={...raw,...normalizeSectionLayout(raw)},heading=`${s.showTitle?`<${index===0&&s.type==='hero'?'h1':'h2'}>${esc(localized(s,'title'))}</${index===0&&s.type==='hero'?'h1':'h2'}>`:''}${s.showSubtitle?`<p>${esc(localized(s,'subtitle'))}</p>`:''}`;
  let content='';
  if(s.type==='imageBanner')content=`<section class="sf-image-only-banner sf-clickable-surface">${img(s.image)}${hit({...s,clickable:true})}</section>`;
  if(s.type==='hero'||s.type==='image')content=`<section class="sf-image-section sf-clickable-surface ${s.type==='hero'?'sf-custom-hero':''}">${hit(s)}${s.showImage?img(s.image):''}<div>${heading}<div class="sf-section-actions">${button(s)}${s.showAllProducts?allButton:''}</div></div></section>`;
  if(s.type==='text'||s.type==='cta')content=`<section class="sf-text-section">${heading}${button(s)}</section>`;
  if(['benefits','steps','faq'].includes(s.type)){const entries=localized(s,'items').split('\n').filter(Boolean);content=`<section class="sf-section">${heading}<div class="sf-custom-items">${entries.map((line,i)=>{const [title,...desc]=line.split('|');return s.type==='faq'?`<details><summary>${esc(title)}</summary><p>${esc(desc.join('|'))}</p></details>`:`<article>${s.type==='steps'?`<b>${i+1}</b>`:''}<h3>${esc(title)}</h3><p>${esc(desc.join('|'))}</p></article>`;}).join('')}</div></section>`;}
  if(s.type==='products')content=`<section class="sf-section">${heading}<div class="sf-products">${selectSectionProducts(state.publicOffers||[],s,config.collections).map(p=>storeProductCard(p,{...h,showProductImage:s.showImage},options.money,lang)).join('')||`<p class="sf-empty">${en?'No products available.':'لا توجد منتجات متاحة.'}</p>`}</div><div class="sf-section-actions">${button(s)}${s.showAllProducts?allButton:''}</div></section>`;
  if(s.type==='catalog')content=`<section class="sf-section sf-main-catalog" id="store-catalog">${heading}<div data-store-catalog-slot>${options.catalog??`<div class="sf-products">${(state.publicOffers||[]).filter(p=>p.status==='published'&&!p.deletedAt).map(p=>storeProductCard(p,{...h,showProductImage:s.showImage},options.money,lang)).join('')}</div>`}</div></section>`;
  if(s.type==='categories')content=`<section class="sf-section">${heading}<div class="sf-categories">${(state.settings.categories||[]).filter(c=>c.active!==false).map(c=>`<button type="button" data-store-category="${esc(c.id)}">${s.showImage?img(s.categoryImages?.[c.id])||`<span class="sf-category-placeholder">${symbol('box')}</span>`:''}<strong>${esc(en?c.nameEn:c.nameAr)}</strong></button>`).join('')}</div></section>`;
  if(s.type==='banners')content=`<section class="sf-section">${heading}<div class="sf-banners">${(config.banners||[]).filter(b=>b.active&&(b.channel==='both'||b.channel===channel)&&(!b.start||b.start<=today)&&(!b.end||b.end>=today)).map(b=>`<article class="sf-banner sf-clickable-surface">${hit({...s,...b,clickable:!!b.href,buttonTarget:'link'})}${s.showImage?img(b.image):''}<div><h3>${esc(localized(b,'title'))}</h3><p>${esc(localized(b,'subtitle'))}</p>${button({...s,...b,buttonTarget:b.href?'link':'products'})}</div></article>`).join('')}</div></section>`;
  if(s.type==='footer')content=`<footer class="sf-footer">${heading}<div class="sf-contact">${s.email?`<a href="mailto:${esc(s.email)}">${esc(s.email)}</a>`:''}${s.phone?`<a href="https://wa.me/${esc(s.phone.replace(/\D/g,''))}" dir="ltr">${esc(s.phone)}</a>`:''}</div>${button(s)}${!options.client&&h.showSupplierRegister?`<button data-store-action="register-supplier">${en?'Join as a supplier':'انضم كمورد'}</button>`:''}</footer>`;
  if(s.type==='divider')content='<hr>';
  return `<div class="sf-layout-block sf-layout-${s.layout} ${s.desktopVisible?'':'sf-hide-desktop'} ${s.mobileVisible?'':'sf-hide-mobile'}" data-layout-section="${esc(s.id)}" data-image-side="${s.imageSide}" style="--section-bg:${s.background};--section-color:${s.textColor};--section-columns:${s.columns};--section-mobile-columns:${s.mobileColumns};--section-gap:${s.gap}px;--section-padding:${s.padding}px;--section-margin:${s.margin}px;--section-radius:${s.radius}px;--section-title:${s.titleSize}px;--section-fit:${s.imageFit};text-align:${s.align};max-width:${s.width==='contained'?'1200px':'none'}">${content}</div>`;
 }).join('');
 return `<div class="published-storefront" lang="${en?'en':'ar'}" dir="${en?'ltr':'rtl'}" style="--store-accent:${color}">${localized(t,'announcement')?`<div class="sf-announcement">${esc(localized(t,'announcement'))}</div>`:''}${header}${config.links?.length?`<nav class="sf-nav">${config.links.map(l=>`<button type="button" data-store-page="${esc(l.target)}">${esc(localized(l,'title'))}</button>`).join('')}</nav>`:''}${blocks}</div>`;
}
export function renderProductListing(state,sectionId='all',options={}){
 const lang=options.language||document.documentElement.lang,en=lang==='en',section=(state.settings?.storefront?.sections||[]).find(s=>s.id===sectionId);
 const rows=selectSectionProducts(state.publicOffers||[],sectionId==='all'||!section?{productSource:'latest',limit:100000}:{...section,limit:100000},state.settings?.storefront?.collections||[]);
 const label=sectionId==='all'||!section?(en?'All products':'جميع المنتجات'):(section[en?'titleEn':'title']||section.title);
 return `<div class="published-storefront sf-browse" dir="${en?'ltr':'rtl'}" lang="${lang}"><button type="button" data-store-browse-home>${en?'Back to home':'العودة للرئيسية'}</button><h1>${esc(label)}</h1><p>${rows.length} ${en?'products':'منتج'}</p>${sectionId!=='all'?`<button type="button" data-store-browse="all">${en?'View all products':'عرض جميع المنتجات'}</button>`:''}<div class="sf-products">${rows.map(p=>storeProductCard(p,homeConfig(state.settings),options.money,lang)).join('')||`<p>${en?'No products selected.':'لا توجد منتجات محددة.'}</p>`}</div></div>`;
}
export function bindStorefront(host,state,actions){if(!host)return;let homeHTML,homeNodes;const remember=()=>{if(!homeNodes){homeNodes=[...host.childNodes];homeHTML=host.innerHTML;}};host.onclick=e=>{const browse=e.target.closest('[data-store-browse]'),back=e.target.closest('[data-store-browse-home]');if(back){host.replaceChildren(...homeNodes);homeNodes=null;homeHTML=null;actions.hydrate?.(host);return;}if(browse){e.preventDefault();remember();host.innerHTML=renderProductListing(state,browse.dataset.storeBrowse,{money:actions.money});actions.hydrate?.(host);host.scrollIntoView({behavior:'smooth'});return;}const p=e.target.closest('[data-store-product]'),add=e.target.closest('[data-store-add]'),l=e.target.closest('[data-store-page]'),c=e.target.closest('[data-store-category]'),a=e.target.closest('[data-store-action]');if(add){e.preventDefault();e.stopPropagation();actions.add?.(add.dataset.storeAdd);return;}if(p)actions.product?.(p.dataset.storeProduct);if(c){actions.category?.(c.dataset.storeCategory);actions.catalog?.();}if(a){e.preventDefault();actions.action?.(a.dataset.storeAction);}if(l){if(l.dataset.storePage==='home')actions.action?.('home');else if(l.dataset.storePage==='products'){remember();host.innerHTML=renderProductListing(state,'all',{money:actions.money});actions.hydrate?.(host);host.scrollIntoView({behavior:'smooth'});}else{const content=(state.settings.storefront?.pages||[]).find(x=>x.id===l.dataset.storePage&&x.active);if(content)actions.page?.(content.title,`<p class="long-copy">${esc(content.content)}</p>`);}}};}
