import {catalogConfig,catalogDefaults,CATALOG_CONTROLS,selectedTaxonomy,catalogProducts} from '../../shared/catalog-controls.mjs';
export {catalogConfig,catalogDefaults,CATALOG_CONTROLS};
import {SECTION_DEFAULTS,normalizeSectionLayout,sectionDefaults} from '../../shared/section-layout.mjs';
export {SECTION_DEFAULTS,sectionDefaults};
import {homeConfig,defaultStore,selectSectionProducts,STORE_OPTIONS,safeStoreLink} from '../../shared/storefront-model.mjs';
export {homeConfig,defaultStore,STORE_OPTIONS};
export {selectSectionProducts};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=(p,lang=document.documentElement.lang)=>p.translation?.[lang==='en'?'titleEn':'titleAr']||p.translation?.titleAr||p.product||'';
const media=src=>/^\/api\/media\/[a-f0-9-]{36}$/.test(src||'')?src:'';
export const stageNames=['التحقق من توفر البضاعة','بانتظار الدفع','قيد التجهيز','جاهز للفحص والشحن','تم الشحن','في الطريق','التخليص الجمركي','قيد التوصيل','تم التسليم'];
const stageEnglish=['Checking availability','Awaiting payment','Preparing','Ready for inspection and shipping','Shipped','In transit','Customs clearance','Out for delivery','Delivered'];
export const stageLabel=i=>(document.documentElement.lang==='en'?stageEnglish:stageNames)[i]||'';
export function tierPrice(p,q){let price=Number(p.unitPrice);for(const t of p.tiers||[])if(q>=t.min)price=Number(t.price);return price;}
export function productExtras(p,h={showPrices:true}){return `<section class="product-extra">${[['',p.shortDescription],['المواصفات / Specifications',p.technicalSpecs],['الخيارات / Options',p.options],['ملاحظات / Notes',p.productNotes]].filter(([,v])=>v).map(([label,v])=>`${label?`<h3>${label}</h3>`:''}<p>${esc(v)}</p>`).join('')}${h.showPrices&&p.tiers?.length?`<h3>أسعار الجملة / Wholesale prices</h3><ul>${p.tiers.map(t=>`<li>${t.min}+ : ${t.price} ${esc(p.currency)}</li>`).join('')}</ul>`:''}</section>`;}
export function orderTimeline(o){return `<section class="flow-timeline">${o.cancelledAt?`<p>ملغى / Cancelled: ${esc(o.cancellationReason)}</p>`:''}<ol>${stageNames.map((n,i)=>{const event=(o.orderHistory||[]).find(h=>h.stage===i&&!h.cancelled);return `<li class="${i<o.orderStage?'done':i===o.orderStage?'current':''}" ${i===o.orderStage?'aria-current="step"':''}><strong>${esc(stageLabel(i))}</strong><small>${event?esc(new Date(event.at).toLocaleString()):'—'}</small></li>`}).join('')}</ol><p>${esc(o.carrier||'')} ${esc(o.trackingNumber||'')}</p><p>${esc(o.delivery?.country||'')} · ${esc(o.delivery?.address||'')}</p></section>`;}
const symbol=n=>({cart:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 3h2l3 12h10l3-9H6M9 21h.01M18 21h.01"/></svg>',arrow:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M19 12H5m6-6-6 6 6 6"/></svg>',box:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><path d="m3 7 9-5 9 5-9 5-9-5v10l9 5 9-5V7M12 12v10M7 4l10 6"/></svg>'}[n]);
export function storeProductCard(p,h,money,lang=document.documentElement.lang){const src=media(p.images?.[0]);return `<article class="sf-product"><button type="button" data-store-product="${esc(p.id)}" class="sf-product-visual" aria-label="${esc(title(p,lang))}">${h.showProductImage===false?'':src?`<img src="${esc(src)}" data-media="${esc(src)}" alt="${esc(title(p,lang))}" loading="lazy">`:`<span class="sf-placeholder">${symbol('box')}</span>`}${h.showOrigin===false?'':`<span class="sf-origin">${esc(p.country||'')}</span>`}</button><div class="sf-product-copy"><button type="button" data-store-product="${esc(p.id)}" class="sf-product-name">${esc(title(p,lang))}</button><div class="sf-product-meta">${h.showMoq===false?'':`<span>MOQ ${esc(p.moq||1)}</span>`}${h.showStock&&p.stock!==''&&p.stock!=null?`<span>${esc(lang==='en'?'Stock':'المخزون')}: ${esc(p.stock)}</span>`:''}</div><div class="sf-product-bottom">${h.showPrices?`<div class="sf-price"><strong>${money?money(p.unitPrice,p.currency):esc(new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(Number(p.unitPrice)||0))}</strong><small>${money?'':esc(p.currency||'')}</small></div>`:''}${h.showCart?`<button type="button" class="sf-add" data-store-add="${esc(p.id)}" aria-label="${esc(lang==='en'?'Add '+title(p,lang)+' to cart':'إضافة '+title(p,lang)+' إلى السلة')}">${symbol('cart')}<span>${lang==='en'?'Add to cart':'أضف للسلة'}</span></button>`:''}</div></div></article>`;}
export function renderStorefront(state,channel='web',options={}){
 const route=options.route??storeRoute();if(route.category||route.page)return renderStoreRoute(state,route,options);
 const config=state?.settings?.storefront||defaultStore(),h=homeConfig(state?.settings),t=config.theme||{},lang=options.language||document.documentElement.lang,en=lang==='en';
 const localized=(o,k)=>o[k+(en?'En':'')]||o[k]||'',img=(src,cls='')=>media(src)?`<img class="${cls}" src="${esc(src)}" data-media="${esc(src)}" alt="" loading="lazy">`:'';
 const color=/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#193d43',name=t.name||'M Platform';
 const button=s=>!s.showButton||!localized(s,'button')?'':s.buttonTarget==='link'?(s.href&&safeStoreLink(s.href)?`<a class="sf-primary" href="${esc(s.href)}">${esc(localized(s,'button'))}</a>`:''):`<button class="sf-primary" type="button" ${s.buttonTarget==='products'?`data-store-browse="${esc(s.id)}"`:`data-store-action="${esc(s.buttonTarget)}"`}>${esc(localized(s,'button'))}${symbol('arrow')}</button>`;
 const allButton=`<button type="button" class="sf-all-products" data-store-browse="all">${en?'View all products':'عرض جميع المنتجات'}</button>`;
 const hit=s=>!s.clickable?'':s.buttonTarget==='link'?(s.href&&safeStoreLink(s.href)?`<a class="sf-banner-hit" href="${esc(s.href)}" aria-label="${esc(localized(s,'title')||localized(s,'button')||(en?'Open banner':'فتح البنر'))}"></a>`:''):`<button type="button" class="sf-banner-hit" ${s.buttonTarget==='products'?`data-store-browse="${esc(s.id)}"`:`data-store-action="${esc(s.buttonTarget)}"`} aria-label="${esc(localized(s,'title')||localized(s,'button')||(en?'Open banner':'فتح البنر'))}"></button>`;
 const header=options.chrome===false?'':renderStoreHeader(state,options);
 const today=new Date().toISOString().slice(0,10);
 const blocks=(config.sections||[]).filter(s=>s.visible&&(s.channel==='both'||s.channel===channel)).map((raw,index)=>{
  const s={...raw,...normalizeSectionLayout(raw)},heading=`${s.showTitle?`<${index===0&&s.type==='hero'?'h1':'h2'}>${esc(localized(s,'title'))}</${index===0&&s.type==='hero'?'h1':'h2'}>`:''}${s.showSubtitle?`<p>${esc(localized(s,'subtitle'))}</p>`:''}`;
  let content='';
  if(s.type==='imageBanner')content=`<section class="sf-image-only-banner sf-clickable-surface">${img(s.image)}${hit({...s,clickable:true})}</section>`;
  if(s.type==='hero'||s.type==='image')content=`<section class="sf-image-section sf-clickable-surface ${s.type==='hero'?'sf-custom-hero':''}">${hit(s)}${s.showImage?img(s.image):''}<div>${heading}<div class="sf-section-actions">${button(s)}${s.showAllProducts?allButton:''}</div></div></section>`;
  if(s.type==='text'||s.type==='cta')content=`<section class="sf-text-section">${heading}${button(s)}</section>`;
  if(['benefits','steps','faq'].includes(s.type)){const entries=localized(s,'items').split('\n').filter(Boolean);content=`<section class="sf-section">${heading}<div class="sf-custom-items">${entries.map((line,i)=>{const [title,...desc]=line.split('|');return s.type==='faq'?`<details><summary>${esc(title)}</summary><p>${esc(desc.join('|'))}</p></details>`:`<article>${s.type==='steps'?`<b>${i+1}</b>`:''}<h3>${esc(title)}</h3><p>${esc(desc.join('|'))}</p></article>`;}).join('')}</div></section>`;}
  if(s.type==='products')content=`<section class="sf-section">${heading}<div class="sf-products">${selectSectionProducts(state.publicOffers||[],s,config.collections).map(p=>storeProductCard(p,{...h,showProductImage:s.showImage},options.money,lang)).join('')||`<p class="sf-empty">${en?'No products available.':'لا توجد منتجات متاحة.'}</p>`}</div><div class="sf-section-actions">${button(s)}${s.showAllProducts?allButton:''}</div></section>`;
  if(s.type==='catalog')content=`<section class="sf-section sf-main-catalog" id="store-catalog">${heading}<div data-store-catalog-slot>${renderCatalog(state,{...options,language:lang})}</div></section>`;
  if(s.type==='categories')content=`<section class="sf-section">${heading}<div class="sf-categories">${selectedTaxonomy(state.settings.categories,s.categoryIds).map(c=>`<a href="/?category=${encodeURIComponent(c.id)}" data-store-category="${esc(c.id)}">${s.showImage?img(s.categoryImages?.[c.id])||`<span class="sf-category-placeholder">${symbol('box')}</span>`:''}<strong>${esc(en?c.nameEn:c.nameAr)}</strong></a>`).join('')}</div></section>`;
  if(s.type==='banners')content=`<section class="sf-section">${heading}<div class="sf-banners">${(config.banners||[]).filter(b=>b.active&&(b.channel==='both'||b.channel===channel)&&(!b.start||b.start<=today)&&(!b.end||b.end>=today)).map(b=>`<article class="sf-banner sf-clickable-surface">${hit({...s,...b,clickable:!!b.href,buttonTarget:'link'})}${s.showImage?img(b.image):''}<div><h3>${esc(localized(b,'title'))}</h3><p>${esc(localized(b,'subtitle'))}</p>${button({...s,...b,buttonTarget:b.href?'link':'products'})}</div></article>`).join('')}</div></section>`;
  if(s.type==='footer')return '';
  if(s.type==='divider')content='<hr>';
  return `<div class="sf-layout-block sf-layout-${s.layout} ${s.desktopVisible?'':'sf-hide-desktop'} ${s.mobileVisible?'':'sf-hide-mobile'}" data-layout-section="${esc(s.id)}" data-image-side="${s.imageSide}" style="--section-bg:${s.background};--section-color:${s.textColor};--section-columns:${s.columns};--section-mobile-columns:${s.mobileColumns};--section-gap:${s.gap}px;--section-padding:${s.padding}px;--section-margin:${s.margin}px;--section-radius:${s.radius}px;--section-title:${s.titleSize}px;--section-fit:${s.imageFit};text-align:${s.align};max-width:${s.width==='contained'?'1200px':'none'}">${content}</div>`;
 }).join('');
 return `<div class="published-storefront" lang="${en?'en':'ar'}" dir="${en?'ltr':'rtl'}" style="--store-accent:${color}">${header}${blocks}${options.chrome===false?'':renderStoreFooter(state,options)}</div>`;
}
export function storeRoute(){const params=new URLSearchParams(typeof location==='undefined'?'':location.search);return {category:params.get('category')||'',page:params.get('page')||''};}
export function renderStoreHeader(state,options={}){
 const config=state?.settings?.storefront||defaultStore(),t=config.theme||{},h=homeConfig(state?.settings),en=(options.language||document.documentElement.lang)==='en',local=(o,k)=>o[en?k+'En':k]||o[k]||'',logo=media(t.logo);
 return `${local(t,'announcement')?`<div class="sf-announcement">${esc(local(t,'announcement'))}</div>`:''}<header class="sf-header"><a href="/" data-store-action="home" class="sf-brand">${logo?`<img src="${esc(logo)}" data-media="${esc(logo)}" alt="${esc(t.name||'')}">`:''}<span>${esc(t.name||'M Platform')}<small>${esc(local(t,'tagline'))}</small></span></a><div class="sf-header-actions">${h.showCart&&!['supplier','admin'].includes(options.role)?`<button type="button" data-store-action="cart">${symbol('cart')}<span>${en?'Cart':'السلة'}</span><b data-store-cart-count>${Number(options.cartCount)||0}</b></button>`:''}${options.role?`<button data-store-action="account">${en?'Account':'الحساب'}</button><button data-store-action="notifications" aria-label="${en?'Notifications':'الإشعارات'}">🔔 ${Number(options.unread)||''}</button><button data-store-action="refresh" aria-label="${en?'Refresh':'تحديث'}">↻</button>`:h.showLogin?`<button data-store-action="login">${en?'Sign in':'تسجيل الدخول'}</button>`:''}<button data-store-action="language">${en?'العربية':'EN'}</button></div></header>${config.links?.length?`<nav class="sf-nav">${config.links.filter(l=>['home','products'].includes(l.target)||(config.pages||[]).some(p=>p.id===l.target&&p.active)).map(l=>`<a href="${l.target==='home'?'/':l.target==='products'?'/?page=products':'/?page='+encodeURIComponent(l.target)}">${esc(local(l,'title'))}</a>`).join('')}</nav>`:''}`;
}
export function renderStoreFooter(state,options={}){
 const config=state?.settings?.storefront||defaultStore(),s=(config.sections||[]).find(s=>s.type==='footer'),en=(options.language||document.documentElement.lang)==='en',local=(o,k)=>o[en?k+'En':k]||o[k]||'';
 if(!s||!s.visible)return '';
 const pages=(config.pages||[]).filter(p=>p.active&&p.footer);
 return `<footer class="sf-footer" data-layout-section="${esc(s.id)}" style="background:${/^#[0-9a-f]{6}$/i.test(s.background)?s.background:'#17363b'};color:${/^#[0-9a-f]{6}$/i.test(s.textColor)?s.textColor:'#e8eeea'}"><div class="sf-footer-grid"><section class="sf-footer-brand">${s.showTitle!==false?`<h2>${esc(local(s,'title'))}</h2>`:''}${s.showSubtitle!==false?`<p>${esc(local(s,'subtitle'))}</p>`:''}</section><nav aria-label="${en?'Shop':'التسوق'}"><h3>${en?'Explore the store':'تسوّق معنا'}</h3><a href="/">${en?'Home':'الرئيسية'}</a><a href="/?page=products">${en?'Browse products':'تصفح المنتجات'}</a>${homeConfig(state.settings).showLogin?`<button data-store-action="${options.role?'account':'login'}">${en?'My account':'حسابي'}</button>`:''}${homeConfig(state.settings).showSupplierRegister?`<button data-store-action="register-supplier">${en?'Become a supplier':'انضم كمورد'}</button>`:''}</nav>${pages.length?`<nav class="sf-policy-links" aria-label="${en?'Site policies':'سياسات الموقع'}"><h3>${en?'Policies & information':'السياسات والمعلومات'}</h3>${pages.map(p=>`<a href="/?page=${encodeURIComponent(p.id)}">${esc(local(p,'title'))}</a>`).join('')}</nav>`:''}${s.email||s.phone?`<section class="sf-footer-contact"><h3>${en?'Contact us':'تواصل معنا'}</h3>${s.email?`<a href="mailto:${esc(s.email)}" dir="ltr">${esc(s.email)}</a>`:''}${s.phone?`<a href="https://wa.me/${esc(s.phone.replace(/\D/g,''))}" dir="ltr">${esc(s.phone)}</a>`:''}</section>`:''}</div><div class="sf-footer-bottom"><small>© ${new Date().getFullYear()} ${esc(local(s,'title')||config.theme?.name||'')} · ${en?'All rights reserved.':'جميع الحقوق محفوظة.'}</small><button data-store-action="language">${en?'العربية':'English'}</button></div></footer>`;
}
export function renderCatalog(state,options={},filters={}){
 const en=(options.language||document.documentElement.lang)==='en',c={...catalogConfig(state.settings),...options.catalogConfig},f={sort:c.sort,...filters,language:en?'en':'ar'};
 if(options.category)f.category=options.category;
 const rows=catalogProducts(state.publicOffers||[],f),pages=Math.max(1,Math.ceil(rows.length/c.pageSize)),page=Math.max(1,Math.min(Number(f.page)||1,pages)),shown=rows.slice((page-1)*c.pageSize,page*c.pageSize),label=r=>r[en?'nameEn':'nameAr']||r.nameAr||r.id;
 const select=(key,title,items,value)=>!items.length?'':`<label>${title}<select data-catalog-filter="${key}" aria-label="${title}">${c.showAll?`<option value="">${en?'All':'الكل'}</option>`:`<option value="" hidden>${en?'Choose':'اختر'}</option>`}${items.map(r=>`<option value="${esc(r.id)}" ${r.id===value?'selected':''}>${esc(label(r))}</option>`).join('')}</select></label>`;
 const search=`${c.showSearch?`<label>${en?'Search':'البحث'}<input type="search" data-catalog-filter="q" aria-label="${en?'Search products':'البحث عن المنتجات'}" placeholder="${en?'Product name, SKU or number':'اسم المنتج أو SKU أو رقم المنتج'}" value="${esc(f.q||'')}"></label>`:''}`;
 return `<div class="sf-catalog-layout sf-filters-${c.filterLayout}"><div class="sf-catalog-tools sf-search-${c.searchPosition}">${search}<div class="sf-catalog-controls">${c.showCategories&&!options.category?select('category',en?'Category':'التصنيف',selectedTaxonomy(state.settings.categories,c.categoryIds),f.category):''}${c.showSubcategories?select('subcategory',en?'Subcategory':'التصنيف الفرعي',selectedTaxonomy(state.settings.subcategories,c.subcategoryIds).filter(x=>!f.category||x.parentId===f.category),f.subcategory):''}${c.showCountries?select('country',en?'Supply country':'بلد التوريد',selectedTaxonomy(state.settings.supplyCountries,c.countryIds),f.country):''}${c.showSort?`<label>${en?'Sort':'الترتيب'}<select data-catalog-filter="sort" aria-label="${en?'Sort':'الترتيب'}">${[['newest',en?'Newest':'الأحدث'],['name',en?'Name':'الاسم'],['price-asc',en?'Price: low to high (per currency)':'السعر تصاعديًا (حسب العملة)'],['price-desc',en?'Price: high to low (per currency)':'السعر تنازليًا (حسب العملة)']].map(([v,t])=>`<option value="${v}" ${f.sort===v?'selected':''}>${t}</option>`).join('')}</select></label>`:''}${c.showReset?`<button data-catalog-reset>${en?'Clear filters':'مسح الفلاتر'}</button>`:''}</div></div><div class="sf-catalog-results">${c.showCount?`<p role="status">${rows.length} ${en?'products':'منتج'}</p>`:''}<div class="sf-products">${shown.map(p=>storeProductCard(p,c,options.money,en?'en':'ar')).join('')||`<p>${en?'No matching products.':'لا توجد منتجات مطابقة.'}</p>`}</div>${pages>1?`<nav class="product-pagination">${c.showPagination?`<button data-catalog-page="${page-1}" ${page===1?'disabled':''}>${en?'Previous':'السابق'}</button><span>${page} / ${pages}</span><button data-catalog-page="${page+1}" ${page===pages?'disabled':''}>${en?'Next':'التالي'}</button>`:`${page<pages?`<button data-catalog-page="${page+1}">${en?'Next products':'المنتجات التالية'}</button>`:''}${page>1?`<button data-catalog-page="${page-1}">${en?'Previous products':'المنتجات السابقة'}</button>`:''}`}</nav>`:''}</div></div>`;
}
export function renderStoreRoute(state,route,options={}){
 const en=(options.language||document.documentElement.lang)==='en',config=state.settings?.storefront||defaultStore();let content='';
 if(route.category){const c=(state.settings.categories||[]).find(c=>c.id===route.category&&c.active!==false);content=c?`<h1>${esc(c[en?'nameEn':'nameAr']||c.nameAr)}</h1><div data-store-catalog-slot data-fixed-category="${esc(c.id)}">${renderCatalog(state,{...options,category:c.id})}</div>`:`<h1>${en?'Category unavailable':'التصنيف غير متاح'}</h1>`;}
 else if(route.page==='products')content=`<h1>${en?'All products':'جميع المنتجات'}</h1><div data-store-catalog-slot>${renderCatalog(state,options)}</div>`;
 else {const p=config.pages?.find(p=>p.id===route.page&&p.active);content=p?`<h1>${esc(p[en?'titleEn':'title']||p.title)}</h1><div class="sf-policy-content">${esc(p[en?'contentEn':'content']||p.content)}</div>`:`<h1>${en?'Page unavailable':'الصفحة غير متاحة'}</h1>`;}
 return `<div class="published-storefront" dir="${en?'ltr':'rtl'}">${options.chrome===false?'':renderStoreHeader(state,options)}<main class="sf-route"><a href="/">${en?'Home':'الرئيسية'}</a>${content}</main>${options.chrome===false?'':renderStoreFooter(state,options)}</div>`;
}
export function renderProductListing(state,sectionId='all',options={}){
 const s=state.settings?.storefront?.sections?.find(s=>s.id===sectionId),subset=sectionId==='all'?state:{...state,publicOffers:selectSectionProducts(state.publicOffers||[],{...s,limit:100000},state.settings?.storefront?.collections)};
 return renderStoreRoute(subset,{page:'products'},options);
}
export function bindStorefront(host,state,actions){
 if(!host)return;let filters={},catalogState=state;const redraw=()=>{const slot=host.querySelector('[data-store-catalog-slot]');if(!slot)return;slot.innerHTML=renderCatalog(catalogState,{money:actions.money,category:slot.dataset.fixedCategory},filters);actions.hydrate?.(host);};
 host.oninput=e=>{const el=e.target;if(el.dataset.catalogFilter!=='q')return;const start=el.selectionStart;filters.q=el.value;filters.page=1;redraw();const input=host.querySelector('[data-catalog-filter="q"]');input?.focus();try{input?.setSelectionRange(start,start);}catch{}};
 host.onchange=e=>{const k=e.target.dataset.catalogFilter;if(!k||k==='q')return;filters[k]=e.target.value;filters.page=1;if(k==='category')filters.subcategory='';redraw();};
 host.onclick=e=>{
  const page=e.target.closest('[data-catalog-page]'),reset=e.target.closest('[data-catalog-reset]');if(page){filters.page=Number(page.dataset.catalogPage);redraw();return;}if(reset){filters={};redraw();return;}
  const browse=e.target.closest('[data-store-browse]'),p=e.target.closest('[data-store-product]'),add=e.target.closest('[data-store-add]'),l=e.target.closest('[data-store-page]'),c=e.target.closest('[data-store-category]'),a=e.target.closest('[data-store-action]');
  if(browse){e.preventDefault();const section=state.settings?.storefront?.sections?.find(s=>s.id===browse.dataset.storeBrowse);catalogState=browse.dataset.storeBrowse==='all'?state:{...state,publicOffers:selectSectionProducts(state.publicOffers||[],{...section,limit:100000},state.settings?.storefront?.collections)};host.innerHTML=renderProductListing(state,browse.dataset.storeBrowse,{money:actions.money,chrome:actions.chrome});filters={};actions.hydrate?.(host);return;}
  if(add){e.preventDefault();e.stopPropagation();actions.add?.(add.dataset.storeAdd);return;}
  if(p)actions.product?.(p.dataset.storeProduct);
  if(c){e.preventDefault();location.assign('/?category='+encodeURIComponent(c.dataset.storeCategory));}
  if(a){e.preventDefault();if(a.dataset.storeAction==='home'){location.assign('/');return;}actions.action?.(a.dataset.storeAction);}
  if(l)location.assign(l.dataset.storePage==='home'?'/':'/?page='+encodeURIComponent(l.dataset.storePage));
 };
}
